Gym.create(name:'Climb Central Funan')
Gym.create(name:'Climb Central Sports Hub')
Gym.create(name:'Climb Central Novena')
Gym.create(name:'Climb Central Katong')
Gym.create(name:'Ground Up')
Gym.create(name:'Boulder World')
